---
kind: pipeline
name: build
steps:
- commands:
  - make build
  image: zachfi/build-image
  name: build
  pull: always
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/tags/v*
---
kind: signature
hmac: c10d27152cff3beefdf26d8c560591f50b7958292153192749d281a5b683a277

...
