---
kind: pipeline
name: build
steps:
- commands:
  - make build
  image: zachfi/shell:latest
  name: build
---
kind: signature
hmac: e55c382bd5685a19d2b2cd40e06cfa44f08fee7eea3f455d42dc88dcd457b89b

...
