---
kind: pipeline
name: build
steps:
- commands:
  - make build
  image: zachfi/build-image
  name: build
  pull: always
---
kind: signature
hmac: 32dd34e94c5bc8930ec3b2d5ae2a751e7bfbb53ed8e23cb4d0c4a574b9d55a04

...
